### ISSUE TITLE
Proper handling of cancellation task is needed.

### ISSUE THREAD

**Issue by temirrr** [lablup/callosum#5]
In `Peer` class, in `_recv_loop` method, when `RPCMessageTypes.CANCEL` message arrives, we immediately `await` on the cancellation coroutine. However, it would be better to do smth like `asyncio.create_task` for it. Then, all the proper handling of that task is needed to be done. For example, cancel it on Peer `close` method call, or stop tracking it when the cancellation coroutine is finished.

**Comment by achimnol** [comment]
Now implemented.
@temirrr  I discovered that we have missed calling `heap.heapify(self._pending[okey])` when cancelling and removing a job from the pending list.
